import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const saira = Saira({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Capputeeno",
  description: "Generated by Capputeeno",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={saira.className}>
        <div id="root">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
